apiVersion: v1
kind: Pod
metadata:
  name: mypod
  labels: 
    app: testapp
    env: dev
spec:
 containers:
 - image: k8s.gcr.io/echoserver:1.10
   name: echoserver
   ports:
   - containerPort: 8080
     protocol: TCP